AcmeStoreBundle:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /acme/store

AcmeTaskBundle:
    resource: "@AcmeTaskBundle/Resources/config/routing.yml"
    prefix:   /acme

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
